/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "extract.py", line 218, in <module>
    filter_pred=len_filter
  File "/home/sanne/.local/lib/python3.5/site-packages/torchtext/data/dataset.py", line 161, in __init__
    with io.open(os.path.expanduser(path), encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/Data-loop/train_location_mask.txt'
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2ba4ddbb5f98>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2ba4ddbb5208>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle object at 0x2ba4ddbb5710>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroy'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
ls: cannot access 'Model-DC-loc-loop': No such file or directory
Traceback (most recent call last):
  File "test-DC.py", line 153, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'Model-DC-loc-loop/trainer_states.pt'
